### ISSUE TITLE
Rollup: 'InfiniteScrollModule' is not exported by node_modules/angular2-infinite-scroll/angular2-infinite-scroll.js

### ISSUE THREAD

**Issue by EgorBurykin** [rollup/rollup-plugin-commonjs#135]
Hello, i'am not sure is it issue of angular2-infinite-scroll (0.2.6) itself or rollup-plugin-commonjs(5.0.5). I just can't make Rollup after AOT compilation work. Code rollup.js:

```
plugins: [
    nodeResolve({jsnext: true, module: true}),
    commonjs({
        include: ['node_modules/rxjs/**','node_modules/angular2-infinite-scroll/src/**'],
        namedExports: { 
            'node_modules/angular2-infinite-scroll/angular2-infinite-scroll.js': [ 'InfiniteScrollModule' ]
        }
    }),
    uglify()
]
```

And in my module:

```
import { InfiniteScrollModule } from 'angular2-infinite-scroll/angular2-infinite-scroll';
```

And in system.config.js:

```
map: {
//...
    'angular2-infinite-scroll': 'npm:angular2-infinite-scroll'
}
```

Repo with minimal code to reproduce problem:
[https://github.com/EgorBurykin/angular2-infinite-scroll-problem](https://github.com/EgorBurykin/angular2-infinite-scroll-problem)

**Comment by Rich-Harris** [comment]
Thanks for the repro – unfortunately I can't run it, I get the following trace when I try to run `ngc`:

```bash
TypeError: compiler.createAotCompiler is not a function
    at Function.CodeGenerator.create (/Users/rharris/Documents/www/ROLLUP/commonjs-gh-135/node_modules/@angular/compiler-cli/src/codegen.js:81:36)
    at codegen (/Users/rharris/Documents/www/ROLLUP/commonjs-gh-135/node_modules/@angular/compiler-cli/src/main.js:7:36)
    at Object.main (/Users/rharris/Documents/www/ROLLUP/commonjs-gh-135/node_modules/@angular/tsc-wrapped/src/main.js:47:16)
    at main (/Users/rharris/Documents/www/ROLLUP/commonjs-gh-135/node_modules/@angular/compiler-cli/src/main.js:13:16)
    at Object.<anonymous> (/Users/rharris/Documents/www/ROLLUP/commonjs-gh-135/node_modules/@angular/compiler-cli/src/main.js:29:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
Compilation failed
```

**Comment by EgorBurykin** [comment]
I guess it's because of version of compiler you are using doesn't work with version of typescript > 2.0.3. I fixed bug above in lib like that by modifying index.ts file - adding explicit name exporting, i.e "export {name} from ..." instead of "export * from ..."

**Comment by Rich-Harris** [comment]
@EgorBurykin What index.ts file?

**Comment by DanielJoyce** [comment]
You probably need to install the compiler cli tools

make sure @angular/compiler and @angular/compiler-cli are in your package.json dependencies.

Also typescript version needs to be 2.0.10

Yes, I am having a similar problem on a angular component as well. Its built as a commonjs module and namedExports doesn't work

**Comment by Rich-Harris** [comment]
Looks like this can be closed, let me know if otherwise
