### ISSUE TITLE
Cannot find module 'rollup-plugin-commonjs'

### ISSUE THREAD

**Issue by Josiah** [rollup/rollup-plugin-commonjs#1]
I know this is an experimental project, but I thought you might like to know that it doesn't work using `gulp-rollup` on node v4.2.1.

```
Error: Cannot find module 'rollup-plugin-commonjs'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/josiah/tatb/ecom/gulpfile.js:16:24)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

It looks like the `dist` folder is missing from the NPM package.

**Comment by Rich-Harris** [comment]
Whoops! The perils of using `npm link` to test stuff. Fixed in 0.1.1 – thanks
