### ISSUE TITLE
v5 node.declaration.gatherPossibleValues is not a function

### ISSUE THREAD

**Issue by fczuardi** [rollup/rollup-plugin-commonjs#111]
(copy of https://github.com/rollup/rollup/issues/957 since I dont know where to report)

After upgrading rollup-plugin-commonjs from 4.1.0 to 5.0.0 I start getting this error:

```
node.declaration.gatherPossibleValues is not a function
TypeError: node.declaration.gatherPossibleValues is not a function
    at callHasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/nodes/shared/callHasEffects.js:51:23)
    at CallExpression.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/nodes/CallExpression.js:29:10)
    at Node.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/Node.js:58:32)
    at ParenthesizedExpression.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/Node.js:58:32)
    at Node.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/Node.js:58:32)
    at VariableDeclarator.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/nodes/VariableDeclarator.js:54:33)
    at VariableDeclaration.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/Node.js:54:27)
    at Module.run (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/Module.js:320:14)
    at /Users/fabricio/calamar/open/controltower/node_modules/rollup/src/Bundle.js:134:14
    at Array.forEach (native)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

I am still not sure if this is an issue with my config, with rollup or with rollup-plugin-commonjs, I will investigate it further and try to come up with a simplified test case, just pasting this here to raise a flag for now...

**Comment by ashbrowning** [comment]
I'm also experiencing this in v5.0.5 (but not v4.1.0). I've managed to narrow the issue down to having a function required in as a global dependency (using CommonJS syntax) and having that function invoked in more than one module:

```javascript
//module1.js
'use strict';
var foo = require('foo');
//this works fine
foo(function() {});

//module2.js
'use strict';
var foo = require('foo');
//This second invocation will throw the error
foo(function() {});
```

I've set up a repo that demonstrates this issue - https://github.com/ashbrowning/rollup-plugin-commonjs-gatherPossibleValues

**Comment by Rich-Harris** [comment]
Sorry for the delay – this is a bug in Rollup itself, so I'll close this in favour of https://github.com/rollup/rollup/issues/957
