### ISSUE TITLE
Failed to build with 8.4.0

### ISSUE THREAD

**Issue by bigtimebuddy** [rollup/rollup-plugin-commonjs#299]
When trying to build with the latest version of this plugin, I received a build error 
```
[!] (commonjs plugin) TypeError: parse is not a function in ...
```
This seems to be happening internally in the commonjs plugin. No issues when using 8.3.0.

Using with Rollup v0.52.0

**Comment by BadRed** [comment]
Same here.

**Comment by lukastaegert** [comment]
Sorry for this inconvenience. The reason is that you also need to update the rollup dependency beyond  0.56.0 for 8.4.0 to work as it relies on new functionality introduced there. That being said, I should have made this a major version instead of a minor version due to this dependency, again my apologies!

**Comment by lukastaegert** [comment]
I guess we should make rollup a peer-dependency so that we can specify a version range.

**Comment by schmidtk** [comment]
Would it be worthwhile to unpublish 8.4.0 and publish as 9.0.0 instead? Given it was released today, that should fix folks broken by the change without causing further headaches.

**Comment by bigtimebuddy** [comment]
I aggree @lukastaegert, if you have plugins that depend on a very specific version of Rollup, there should be a peer-dependency in the package. That way users will get a warning.

**Comment by bigtimebuddy** [comment]
In addition to more strict usage of semver and defining peer dependencies, maybe a larger structural change that might help control for these breakages is to reorganize Rollup and it's first-class plugins into a mono-repo (like Babel, et al). That way you release and test everything at the same time and avoid down-stream breakages.

**Comment by lukastaegert** [comment]
I've been thinking about this myself and I think this should be the way to go in the future. However for this specific problem, the releases were done in order. I just did not consider that the update 8.3.0 -> 8.4.0 is not the same as the update 0.55.0 -> 0.56.0. Anyway, I guess I will implement @schmidtk's suggestion.

**Comment by lukastaegert** [comment]
Ok, step 1 is done. 8.3.0 has now been re-published as 8.4.1.

**Comment by bigtimebuddy** [comment]
Cool @lukastaegert, thanks for being so responsive to this!

**Comment by schmidtk** [comment]
Second that, thank you for the quick turn around!

**Comment by tezzutezzu** [comment]
Still having this issue with rollup v0.57 and rollup-plugin-commonjs v9.1.0

**Comment by jakearchibald** [comment]
https://github.com/rollup/rollup-plugin-commonjs/issues/307

**Comment by pumanitro** [comment]
I got the same error with "rollup-plugin-commonjs": "^9.2.0" version but updated "rollup" dependency to the newest one solved my problems (for not it was "rollup": "^0.67.4",)
