### PR TITLE
Use parse method from transform context

### LINKED ISSUE #275: Spread operator in object literal causes SyntaxError
Any module with a spread operator in an object literal will cause a SyntaxError.
This is because [Acorn](https://github.com/acornjs/acorn) doesn't support the spread operator in object literals (https://github.com/acornjs/acorn/issues/388) and all modules are parsed by [Acorn](https://github.com/acornjs/acorn) since https://github.com/rollup/rollup-plugin-commonjs/commit/b9191ae30d1fce2e11da1f014a7a01aa119a77b6. 
Before that the `checkFirstpass` function provided an early exit. 

Reduced test case:

*index.js*
```js
const obj = { foo: 'bar' };
const clone = { ...obj };
```

*rollup.config.js*
```js
import commonjs from 'rollup-plugin-commonjs';

export default {
  input: 'index.js',
  output: {
    format: 'cjs',
  },
  plugins: [commonjs()],
};
```
Yields `[!] (commonjs plugin) SyntaxError: Unexpected token`

### PR DESCRIPTION
**Pull request by KingHenne**
This depends on https://github.com/rollup/rollup/pull/1945. It removes acorn as a dependency (though it's still a dev dependency for the tests) and uses the `parse` method that is exposed via the `transform` context instead.

fixes #275 (by providing the `acornInjectPlugins` option to rollup)
(maybe others?)
closes #237

TODO:

- [x] change `rollup` version to `0.56.0` when it has been published

### CODE REVIEW

**Comment by KingHenne** [comment]
I updated rollup to 0.56 and the tests are passing. @lukastaegert This is now ready for a review.

**Comment by victoriafrench** [comment]
is there some sort of config change needed for this. I am using `rollup` `0.56.4` and am working correctly on `rollup-plugin-commonjs` `8.3.0`. Any version above that (`8.4.0`, `8.4.1`, `9.0.0`) breaks the build with `parse is not a function`

**Comment by rockerest** [comment]
I am having the exact same issue as @victoriafrench.

Any version later than `8.3.0` of this plugin throws `parse is not a function`.

**Comment by lukastaegert** [comment]
@victoriafrench `8.4.1` should actually be working as it is identical to `8.3.0` (if I released it correctly). Otherwise I would assume that you are sharing @rockerest's issue i.e. you are unknowingly consuming rollup via a secondary dependency that pulls in an older version. In this case, please open an issue for that dependency.

If you can confirm that `8.4.1` really does not work, please let me know so that I can attempt another fix.
